name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  testing:
    name: Testing
    uses: OpenTTD/actions/.github/workflows/rw-entry-testing-docker-py.yml@v5
    with:
      python-path: master_server
      python-version: 3.8

  regression:
    name: Regression
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Set up packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.test
        pip install -r requirements.txt

    - name: Regression
      shell: bash
      run: |
        PYTHONPATH=. pytest
